// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZiH5Q2WzeaTB9Xlk43qsp8ASrOM-4R8',
    appId: '1:1004283458149:web:web-app-id',
    messagingSenderId: '1004283458149',
    projectId: 'rtg-b-be4b4',
    authDomain: 'rtg-b-be4b4.firebaseapp.com',
    storageBucket: 'rtg-b-be4b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZiH5Q2WzeaTB9Xlk43qsp8ASrOM-4R8',
    appId: '1:1004283458149:android:d7507c04be71dc50f24c8c',
    messagingSenderId: '1004283458149',
    projectId: 'rtg-b-be4b4',
    storageBucket: 'rtg-b-be4b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZiH5Q2WzeaTB9Xlk43qsp8ASrOM-4R8',
    appId: '1:1004283458149:ios:ios-app-id',
    messagingSenderId: '1004283458149',
    projectId: 'rtg-b-be4b4',
    storageBucket: 'rtg-b-be4b4.firebasestorage.app',
    iosBundleId: 'com.example.rtgVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZiH5Q2WzeaTB9Xlk43qsp8ASrOM-4R8',
    appId: '1:1004283458149:ios:macos-app-id',
    messagingSenderId: '1004283458149',
    projectId: 'rtg-b-be4b4',
    storageBucket: 'rtg-b-be4b4.firebasestorage.app',
    iosBundleId: 'com.example.rtgVendorApp',
  );
}


